### ISSUE TITLE
Setting recurring contribution unit in a priceset is not saved

### ISSUE THREAD

**Issue by shaneonabike** [agileware/au.com.agileware.pricesetfrequency#1]
Hey!

Thanks for building this plugin! This is really after to help members who can't pay the full amount upfront, but rather place it in installments. I already had items in a price field, and then went ahead an added a new one.

Basically, if we have one membership costing $750, and I wanted to add another that was spread over three payments (so every 4 months). When I set that though, and save the field it doesn't seem to save. Will this only work with Donation or can I use it with Member Dues as well?

Thanks!

Agileware Ref: CIVIPF-30

**Comment by shaneonabike** [comment]
I should mention that I am using 5.33.2 so I'm not sure whether this will mesh properly?

**Comment by agileware-justin** [comment]
Hi @shaneonabike - I've been able to save a priceset with recurring membership price option. Can you provide a screenshot of the priceset options? May provide a clue.

**Comment by shaneonabike** [comment]
You bet! Finally, my client decided not to go with this approach but I still want to make sure it works if ever the case we decide to go back.

Initial priceset fields
![Selection_004](https://user-images.githubusercontent.com/1126026/105194983-80984800-5b10-11eb-8ad0-4f80c14006a4.jpg)

Setting the field
![Selection_005](https://user-images.githubusercontent.com/1126026/105195085-a1f93400-5b10-11eb-814b-70a89768e574.jpg)

After I save and re-edit
![Selection_006](https://user-images.githubusercontent.com/1126026/105195218-cf45e200-5b10-11eb-9e6a-d7d228d9dcba.jpg)

But a thought occurred to me actually! Does the membership type need to be set to auto-renew? In my case they are not because we don't want it to auto-renew after one year. Here's a snapshot of the membership I was attempting to add

![Selection_007](https://user-images.githubusercontent.com/1126026/105195488-0fa56000-5b11-11eb-822d-755981f1d2cf.jpg)

**Comment by agileware-justin** [comment]
Thanks @shaneonabike I'll see if we can replicate this problem in our test system.

**Comment by agileware-justin** [comment]
I have tested on CiviCRM 5.32.1 and it's working. See below. Will try and test on 5.33.2 a well.

![Screenshot_20210122_094807](https://user-images.githubusercontent.com/58866555/105421954-0d6d0e00-5c97-11eb-9e6f-4268a86a0ffe.png)

**Comment by shaneonabike** [comment]
Weird. Is there some setting with relation to your Financial Type or membership type that I am missing? I keep trying and still not happening. 

Is it because the Membership Type needs to have Auto-Renew set.? I didn't have it set previously but then set it to Give option but that didn't work.

![Selection_004](https://user-images.githubusercontent.com/1126026/105434633-4de67080-5c32-11eb-8753-76fb41c7587a.jpg)

**Comment by agileware-justin** [comment]
@shaneonabike 

> Weird. Is there some setting with relation to your Financial Type or membership type that I am missing? I keep trying and still not happening.

Not that I can see.

> Is it because the Membership Type needs to have Auto-Renew set.? I didn't have it set previously but then set it to Give option but that didn't work.

No auto-renew is not required.


Please note that to utilise Monthly Terms you really must specify in the Membership Type, each Membership Type Duration Unit is 1 month. So then the Price Set Option would then be configured to renew 1 month term for each reoccurrence.

In your screenshot, the Membership Type Duration Unit was set to 1 year.

**Comment by shaneonabike** [comment]
Ok that is the problem then!~

I modified the documentation and created a pull request so that it might be clearer for future folks.

#2

**Comment by agileware-justin** [comment]
Thanks @shaneonabike merged #2
